In [2]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.



   ---------------------------------------- 0.0/203.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/203.0 MB 2.6 MB/s eta 0:01:17
   ---------------------------------------- 0.4/203.0 MB 4.5 MB/s eta 0:00:46
   ---------------------------------------- 0.6/203.0 MB 5.7 MB/s eta 0:00:36
   ---------------------------------------- 1.0/203.0 MB 6.5 MB/s eta 0:00:32
   ---------------------------------------- 1.4/203.0 MB 7.0 MB/s eta 0:00:29
   ---------------------------------------- 2.0/203.0 MB 7.8 MB/s eta 0:00:26
   ---------------------------------------- 2.5/203.0 MB 8.9 MB/s eta 0:00:23
    --------------------------------------- 3.1/203.0 MB 9.5 MB/s eta 0:00:22
    --------------------------------------- 3.7/203.0 MB 10.4 MB/s eta 0:00:20
    --------------------------------------- 4.5/203.0 MB 11.0 MB/s eta 0:00:19
   - -------------------------------------- 5.3/203.0 MB 12.1 MB/s eta 0:00:17
   - -------------------------------------- 6.2/203.0 MB 12.7 MB/s 

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.5.1+cpu


## 1. Introduction to Tensors

In [5]:
scalar=torch.tensor(7)

In [6]:
type(scalar)

torch.Tensor

In [7]:
#Get tensor back as python int
scalar.item()

7

In [8]:
#Vector
vector=torch.tensor([7,7])
print(vector)
type(vector)

tensor([7, 7])


torch.Tensor

In [9]:
# Matrix
matrix=torch.tensor([[7,7],[6,6],[5,5]])
print(matrix)

tensor([[7, 7],
        [6, 6],
        [5, 5]])


In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 7])

In [12]:
matrix[2][1]

tensor(5)

In [13]:
matrix.shape

torch.Size([3, 2])

In [14]:
# Tensor
TENSOR= torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [18]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2092, 0.8799, 0.9387, 0.1277],
        [0.4379, 0.9157, 0.7675, 0.4591],
        [0.7582, 0.2254, 0.7931, 0.2037]])

In [19]:
random_tensor.ndim

2

In [21]:
#Creating random tensors with similar shape to an image tensor

random_image_tensor=torch.rand(size=(225,225,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([225, 225, 3]), 3)

In [23]:
trial=torch.rand(size=(3,3,3))
trial

tensor([[[0.1682, 0.3090, 0.5722],
         [0.5209, 0.0651, 0.6067],
         [0.3195, 0.7714, 0.2119]],

        [[0.5692, 0.2023, 0.5078],
         [0.2590, 0.4634, 0.7328],
         [0.7122, 0.3806, 0.9488]],

        [[0.3023, 0.3410, 0.9359],
         [0.0665, 0.8390, 0.5436],
         [0.8264, 0.6587, 0.4222]]])

### Zeros and Ones

In [25]:
zero=torch.zeros(size=(3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
one=torch.ones(size=(3,3))
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
one.dtype

torch.float32

### Range

In [28]:
#Creating a range of tensors and tensors-like

In [30]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

### Tensors like

In [32]:
#Creating tensors like

ten_zeros=torch.zeros_like(torch.arange(1,10,2))


In [33]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [34]:
torch.ones_like(torch.arange(1,10,2))

tensor([1, 1, 1, 1, 1])

In [36]:
## Tensor Data Types 

float_32=torch.tensor([3.0,4,9])
float_32.dtype

torch.float32

### TO find details about tensor

In [40]:


some_tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
some_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.ndim)
print(some_tensor.device)

torch.Size([3, 3])
torch.int64
2
cpu


In [43]:
some_tensor=torch.randint(size=(3,3),low=1,high=50)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.ndim)
print(some_tensor.device)

torch.Size([3, 3])
torch.int64
2
cpu


###  Manipulating Tensors (tensor operations)

#### Addition, Multiplication, Subtraction, DIvision, MAtrix Multiplication

In [44]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [45]:
tensor*10

tensor([10, 20, 30])

In [46]:
tensor-10

tensor([-9, -8, -7])

In [47]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [48]:
# Trying pytorch in-built functions

torch.mul(tensor,10)

tensor([10, 20, 30])

### MAtrix Multiplication

In [50]:
## Element wise

matrix=torch.tensor([[1,2],[3,4]])
matrix*2

tensor([[2, 4],
        [6, 8]])

In [56]:
# Two matrix multiplication --this is wrong method

matrix1=torch.tensor([[1,2],[3,4]])
matrix2=torch.tensor([[5,6],[7,8]])

matrix1*matrix2

tensor([[ 5, 12],
        [21, 32]])

In [57]:
torch.matmul(matrix1,matrix2)

tensor([[19, 22],
        [43, 50]])

In [66]:
matrix2

tensor([[5, 6],
        [7, 8]])

In [65]:
matrix2.T


tensor([[5, 7],
        [6, 8]])

### Finding min,max,mean, sum (aggregation in tensor)

In [67]:
x=torch.arange(0,100,10)

In [68]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [70]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [71]:
torch.mean(x),x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [80]:
# mean function wont work on int data type
torch.mean(x.type(torch.float32))

tensor(45.)

### Finding positional min and max of tensors

In [82]:
#returns the position of the max number
torch.argmax(x)

tensor(9)

In [83]:
#returns the position of the min number
torch.argmin(x)

tensor(0)

### Reshaping, Stacking, Squeezing, Unsqueezing

In [84]:
x=torch.arange(1,10)

In [85]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x_new=x.reshape(3,3)

In [87]:
x_new

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [90]:
## Indexing

x=torch.arange(1,10).reshape(1,3,3)

In [91]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [104]:
x[0][2][2]

tensor(9)

In [105]:
x[:,:,2]

tensor([[3, 6, 9]])

In [107]:
x[0,0,0],x[0][0][0]

(tensor(1), tensor(1))

In [114]:
x[:,:,0],    x[:][:][0]

(tensor([[1, 4, 7]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### PyTorch tensors and Numpy

In [115]:
import numpy as np

In [116]:
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [118]:
array+1,tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [120]:
# Tensor to Numpy
new=tensor.numpy()
new

array([1, 2, 3, 4, 5, 6, 7])

### Reproducibility (trying to take random out of random)

##### to reduce the randomness we ca use the *random seed*

In [123]:
torch.manual_seed(42)
tensor1=torch.rand(3,3)
torch.manual_seed(42)
tensor2=torch.rand(3,3)
print(tensor1==tensor2)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [125]:
torch.cuda.is_available()

False