In [ ]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.



   ---------------------------------------- 0.0/203.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/203.0 MB 2.6 MB/s eta 0:01:17
   ---------------------------------------- 0.4/203.0 MB 4.5 MB/s eta 0:00:46
   ---------------------------------------- 0.6/203.0 MB 5.7 MB/s eta 0:00:36
   ---------------------------------------- 1.0/203.0 MB 6.5 MB/s eta 0:00:32
   ---------------------------------------- 1.4/203.0 MB 7.0 MB/s eta 0:00:29
   ---------------------------------------- 2.0/203.0 MB 7.8 MB/s eta 0:00:26
   ---------------------------------------- 2.5/203.0 MB 8.9 MB/s eta 0:00:23
    --------------------------------------- 3.1/203.0 MB 9.5 MB/s eta 0:00:22
    --------------------------------------- 3.7/203.0 MB 10.4 MB/s eta 0:00:20
    --------------------------------------- 4.5/203.0 MB 11.0 MB/s eta 0:00:19
   - -------------------------------------- 5.3/203.0 MB 12.1 MB/s eta 0:00:17
   - -------------------------------------- 6.2/203.0 MB 12.7 MB/s 

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.5.1+cpu


## 1. Introduction to Tensors

In [ ]:
scalar=torch.tensor(7)

In [ ]:
type(scalar)

torch.Tensor

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
print(vector)
type(vector)

tensor([7, 7])


torch.Tensor

In [ ]:
# Matrix
matrix=torch.tensor([[7,7],[6,6],[5,5]])
print(matrix)

tensor([[7, 7],
        [6, 6],
        [5, 5]])


In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 7])

In [ ]:
matrix[2][1]

tensor(5)

In [ ]:
matrix.shape

torch.Size([3, 2])

In [ ]:
# Tensor
TENSOR= torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2092, 0.8799, 0.9387, 0.1277],
        [0.4379, 0.9157, 0.7675, 0.4591],
        [0.7582, 0.2254, 0.7931, 0.2037]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Creating random tensors with similar shape to an image tensor

random_image_tensor=torch.rand(size=(225,225,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([225, 225, 3]), 3)

In [ ]:
trial=torch.rand(size=(3,3,3))
trial

tensor([[[0.1682, 0.3090, 0.5722],
         [0.5209, 0.0651, 0.6067],
         [0.3195, 0.7714, 0.2119]],

        [[0.5692, 0.2023, 0.5078],
         [0.2590, 0.4634, 0.7328],
         [0.7122, 0.3806, 0.9488]],

        [[0.3023, 0.3410, 0.9359],
         [0.0665, 0.8390, 0.5436],
         [0.8264, 0.6587, 0.4222]]])

### Zeros and Ones

In [ ]:
zero=torch.zeros(size=(3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
one=torch.ones(size=(3,3))
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

### Range

In [ ]:
#Creating a range of tensors and tensors-like

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

### Tensors like

In [ ]:
#Creating tensors like

ten_zeros=torch.zeros_like(torch.arange(1,10,2))


In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
torch.ones_like(torch.arange(1,10,2))

tensor([1, 1, 1, 1, 1])

In [ ]:
## Tensor Data Types

float_32=torch.tensor([3.0,4,9])
float_32.dtype

torch.float32

### TO find details about tensor

In [ ]:


some_tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
some_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.ndim)
print(some_tensor.device)

torch.Size([3, 3])
torch.int64
2
cpu


In [ ]:
some_tensor=torch.randint(size=(3,3),low=1,high=50)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.ndim)
print(some_tensor.device)

torch.Size([3, 3])
torch.int64
2
cpu


###  Manipulating Tensors (tensor operations)

#### Addition, Multiplication, Subtraction, DIvision, MAtrix Multiplication

In [ ]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Trying pytorch in-built functions

torch.mul(tensor,10)

tensor([10, 20, 30])

### MAtrix Multiplication

In [ ]:
## Element wise

matrix=torch.tensor([[1,2],[3,4]])
matrix*2

tensor([[2, 4],
        [6, 8]])

In [ ]:
# Two matrix multiplication --this is wrong method

matrix1=torch.tensor([[1,2],[3,4]])
matrix2=torch.tensor([[5,6],[7,8]])

matrix1*matrix2

tensor([[ 5, 12],
        [21, 32]])

In [ ]:
torch.matmul(matrix1,matrix2)

tensor([[19, 22],
        [43, 50]])

In [ ]:
matrix2

tensor([[5, 6],
        [7, 8]])

In [ ]:
matrix2.T


tensor([[5, 7],
        [6, 8]])

### Finding min,max,mean, sum (aggregation in tensor)

In [ ]:
x=torch.arange(0,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x),x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# mean function wont work on int data type
torch.mean(x.type(torch.float32))

tensor(45.)

### Finding positional min and max of tensors

In [ ]:
#returns the position of the max number
torch.argmax(x)

tensor(9)

In [ ]:
#returns the position of the min number
torch.argmin(x)

tensor(0)

### Reshaping, Stacking, Squeezing, Unsqueezing

In [ ]:
x=torch.arange(1,10)

In [ ]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_new=x.reshape(3,3)

In [ ]:
x_new

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
## Indexing

x=torch.arange(1,10).reshape(1,3,3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[0,0,0],x[0][0][0]

(tensor(1), tensor(1))

In [ ]:
x[:,:,0],    x[:][:][0]

(tensor([[1, 4, 7]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### PyTorch tensors and Numpy

In [ ]:
import numpy as np

In [ ]:
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [ ]:
array+1,tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [ ]:
# Tensor to Numpy
new=tensor.numpy()
new

array([1, 2, 3, 4, 5, 6, 7])

### Reproducibility (trying to take random out of random)

##### to reduce the randomness we ca use the *random seed*

In [ ]:
torch.manual_seed(42)
tensor1=torch.rand(3,3)
torch.manual_seed(42)
tensor2=torch.rand(3,3)
print(tensor1==tensor2)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [ ]:
torch.cuda.is_available()

False

## Autograd

In [2]:

import torch

In [7]:
a=torch.tensor([[1,2,3],[4,5,6]],requires_grad=True, dtype=torch.float)
b=a+2
c=2*b*b
out=c.mean()
out.backward()
print(a.grad)

tensor([[2.0000, 2.6667, 3.3333],
        [4.0000, 4.6667, 5.3333]])


In [8]:
a=torch.tensor([[1,2,3],[4,5,6]],requires_grad=True, dtype=torch.float)
b=a+2

In [9]:
b

tensor([[3., 4., 5.],
        [6., 7., 8.]], grad_fn=<AddBackward0>)

In [10]:
c=2*b*b
c

tensor([[ 18.,  32.,  50.],
        [ 72.,  98., 128.]], grad_fn=<MulBackward0>)

In [11]:
c.mean()

tensor(66.3333, grad_fn=<MeanBackward0>)