In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.5.1+cu121


## 1. Introduction to Tensors

In [5]:
scalar=torch.tensor(7)

In [6]:
type(scalar)

torch.Tensor

In [8]:
#Get tensor back as python int
scalar.item()

7

In [9]:
#Vector
vector=torch.tensor([7,7])
print(vector)
type(vector)

tensor([7, 7])


torch.Tensor

In [10]:
# Matrix
matrix=torch.tensor([[7,7],[6,6],[5,5]])
print(matrix)

tensor([[7, 7],
        [6, 6],
        [5, 5]])


In [11]:
matrix.ndim

2

In [12]:
matrix[0]

tensor([7, 7])

In [15]:
matrix[2][1]

tensor(5)

In [14]:
matrix.shape

torch.Size([3, 2])

In [16]:
# Tensor
TENSOR= torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [17]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])